### ISSUE TITLE
Can get uWsApp object?

### ISSUE THREAD

**Issue by karlla1220** [geut/fastify-uws#1]
Thanks for the great library and the example. 

I just wonder how to publish websocket server itself rather than rely on client's reply?

I added "App" property to websocketServer, it seems work, but I want to know there is better way. 

In addition, can we still use UserData or getUserData to identify client? or there is alternative way to distinguish user? Since it does upgrade out-of-box unlike to uws, It is bit confusing though it is very helpful. 

```javascript
addServer(server) {
    const { options } = this;
    const app = (this.App = server[kApp]);
    const listenerHandler = server[kHandler];

    app.ws("/*", {
      compression: options.compression,
      idleTimeout: options.idleTimeout,
...
```

**Comment by tinchoz49** [comment]
Hey @karlla1220, i did an update so you can get access to the uwsApp.

```javascript
import fastify from 'fastify'
import { serverFactory, getUws } from '@geut/fastify-uws'

const app = fastify({
  serverFactory
})

app.addHook('onReady', async () => {
  // access to uws app
  const uwsApp = getUws(app)
})
```
